/**
 * Sibling order, as a rank that merges instead of renumbering.
 *
 * ADR-029 B3 makes the outbox record the BLOCK, so an insert must write one
 * block. An integer index cannot do that: inserting between positions 2 and 3
 * renumbers every block below, which is one queued operation per sibling, and
 * two devices inserting in the same gap both produce index 3 — a tie that
 * last-writer-wins resolves by discarding one block's position rather than
 * placing it.
 *
 * A rank is a string compared lexicographically, and there is always room
 * between two of them: `A` and `B` are adjacent as integers and have `AU`
 * between them as strings. So an insert writes one field on one block, and two
 * concurrent inserts into the same gap produce two different ranks that both
 * survive.
 *
 * **The invariant that keeps that true: a rank never ends in the lowest digit.**
 * `0` is the smallest non-empty string over this alphabet, so nothing sorts
 * before it — a rank of `A0` would be one you can never insert before. Every
 * rank this module returns ends in something higher, which is why the midpoint
 * search descends rather than returning when the midpoint lands on `0`.
 */

/**
 * Ascending in code-point order, which is what string comparison uses. Digits
 * (0x30) before uppercase (0x41) before lowercase (0x61) — so the alphabet's
 * order and the comparison's order are the same, and no custom comparator is
 * needed anywhere that sorts these.
 */
const DIGITS = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
const BASE = DIGITS.length;
const MIDDLE = DIGITS[Math.floor(BASE / 2)]!;

const RANK_SHAPE = /^[0-9A-Za-z]+$/;

/** The rank of a first, only child. */
export const FIRST_RANK = MIDDLE;

export function isRankString(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0 && RANK_SHAPE.test(value);
}

function digit(ch: string): number {
  return DIGITS.indexOf(ch);
}

/**
 * A rank strictly between two neighbours, either of which may be absent.
 *
 * Absent `before` means "insert at the top", absent `after` means "append".
 *
 * **Bad input degrades the ORDER, never the edit.** A rank arrives from a peer
 * and can be corrupt, or the caller's two neighbours can already be out of
 * order after a merge. Throwing there would make a page uneditable because
 * something else was wrong with it, so an unusable bound is ignored and the
 * result may tie with a neighbour — which `compareRank` breaks by id, leaving
 * the block one position from where it was dropped instead of leaving the
 * person unable to type.
 */
export function rankBetween(before: string | null | undefined, after: string | null | undefined): string {
  const lo = isRankString(before) ? before : '';
  const hiGiven = isRankString(after) ? after : '';
  const hi = hiGiven !== '' && lo >= hiGiven ? '' : hiGiven;

  const candidate = midpoint(lo, hi);
  if ((lo === '' || candidate > lo) && (hi === '' || candidate < hi)) return candidate;

  // Only reachable for a bound that breaks the never-end-in-`0` invariant, so
  // only for ranks this module did not produce. Tie rather than misplace: a tie
  // is resolved deterministically by id on both devices, whereas a rank outside
  // the requested gap puts the block somewhere the person did not ask for.
  return hi !== '' ? hi : `${lo}${MIDDLE}`;
}

function midpoint(lo: string, hi: string): string {
  let out = '';
  let bounded = hi !== '';
  // Each pass consumes one character of a bound or of the gap between them, so
  // this terminates; the cap turns a corrupt bound into a wrong answer the
  // caller's own check catches rather than a hang.
  const passes = lo.length + hi.length + 2;

  for (let i = 0; i < passes; i += 1) {
    const da = i < lo.length ? digit(lo[i]!) : -1;
    const db = bounded && i < hi.length ? digit(hi[i]!) : BASE;

    if (db - da > 1) {
      const mid = da + Math.floor((db - da) / 2);
      if (mid > 0) return out + DIGITS[mid];
      // `mid === 0` would end on the lowest digit. Emit it and keep going, so
      // the result is `…0<something>` — still below `hi`, and still leaving
      // room for a later insert before it.
    }

    const next = da >= 0 ? da : 0;
    out += DIGITS[next]!;
    if (bounded && i < hi.length && next < digit(hi[i]!)) bounded = false;
  }
  return out + MIDDLE;
}

/**
 * `count` ranks in order, filling one gap.
 *
 * Used when a paste or an import inserts several blocks at once. Generated by
 * walking the gap rather than by splitting it evenly, so the ranks stay short
 * for the common small paste.
 */
export function rankSequence(
  count: number,
  before: string | null | undefined,
  after: string | null | undefined,
): string[] {
  const out: string[] = [];
  let cursor = before ?? null;
  for (let i = 0; i < count; i += 1) {
    const next = rankBetween(cursor, after);
    out.push(next);
    cursor = next;
  }
  return out;
}

/**
 * Sibling order: rank first, id as the tie-break.
 *
 * The id tie-break is what makes a tied rank harmless — both devices sort the
 * pair the same way, so they agree on the order even though neither chose it.
 * Without it, two blocks with an equal rank would order by whatever the local
 * iteration happened to produce, and the two devices would render the page
 * differently while claiming to be synced.
 */
export function compareRank(a: { rank: string; id: string }, b: { rank: string; id: string }): number {
  if (a.rank !== b.rank) return a.rank < b.rank ? -1 : 1;
  if (a.id === b.id) return 0;
  return a.id < b.id ? -1 : 1;
}
